### ISSUE TITLE
[Shell] The url cannot be null

### ISSUE THREAD

**Issue by ZHUxr233** [hezean/sustc#95]
### Describe your question

As i excute the bootRun, and i input a command, it went wrong. 
>
![image](https://github.com/hezean/sustc/assets/144781216/72ab44dd-0d2c-45c1-81d0-37c3c514cf8e)
Did i miss some configration about connecting the database or something? Please tell me how to solve this problem.

**Comment by hezean** [comment]
ensure your application.yml looks like this

```
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sustc  # change this to your own jdbc url
    username: sustc  # change this to your own username (avoid using a superuser)
    password: sustc  # change this to your own password
```
